# Generated by Django 2.1.5 on 2020-04-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cross',
            field=models.ManyToManyField(related_name='cross', to='joke.Cross'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='hotcross',
            field=models.ManyToManyField(related_name='hotcross', to='joke.HotCross'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picturescross',
            field=models.ManyToManyField(related_name='picturescross', to='joke.PicturesCross'),
        ),
    ]
